### ISSUE TITLE
[Bug] Incorrect URL link for int_github__issue_joined

### ISSUE THREAD

**Issue by jackiexsun** [fivetran/dbt_github#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The line `{{ dbt_utils.concat(["'https://github.com/'",'repository_teams.repository',"'/pull/'", 'issue.issue_number']) }} as url_link,` for generating the url link in int_github__issue_joined is not quite correct because for a Github Issue (not Pull Request), the keyword should be /issues/issue.issue_number (instead of pull/). pull/ is technically ok because the link will redirect to the url with issues/ , but for the purposes of joining across data sources via the url, we need the url to be the actual url (with issues/).

For example, in Fivetran version of this dbt model the link generated for this issue https://github.com/fivetran/engineering/issues/78113 is https://github.com/fivetran/engineering/pull/78113 which redirects to the /issues/ version of the url.

### Expected behavior

The link generated for a Github Issues contains /issues/ not /pull/.

### dbt Project configurations

[](https://github.com/)name: 'prj_production'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran'

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - '{{create_udfs()}}' # Hook that executes macro to create UDFs on run start (look inside the macros folder)

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
      relation: true
      columns: true
  prj_production:
      materialized: view
  zendesk:
    +schema: 'dbt_pkg_zendesk'
  zendesk_source:
    +schema: 'dbt_pkg_zendesk'
  github:
    +schema: 'dbt_pkg_github'
  github_source:
    +schema: 'dbt_pkg_github'
  pendo:
    +schema: 'dbt_pkg_pendo'
  pendo_source:
    +schema: 'dbt_pkg_pendo'

# This section is used for variables for dbt packages
vars: 
  zendesk_source:
    zendesk_schema: zendesk_new
    using_schedules: false        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours
  zendesk:
    using_schedules: false        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/zendesk
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/github
    version: [">=0.3.0", "<0.4.0"]
  - package: fivetran/pendo
    version: [">=0.1.0", "<0.2.0"]  

### What database are you using dbt with?

bigquery

### dbt Version

0.20.2

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as PR #31 addressed the initial issue documented here.
