### ISSUE TITLE
[Feature] Update README

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_github#36]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The README needs to updated to the current format. 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
PR #35 addresses this feature
