### ISSUE TITLE
Missing target schemas config in dbt_package.yml

### ISSUE THREAD

**Issue by rajan-lw** [fivetran/dbt_github#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We have installed the dbt package for github but when we run the models it does not create a target schemas. So comparing the code with Jira package.

In Jira package dbt_package.yml file config
```
models:
  jira:
    +materialized: table
    +schema: jira
    intermediate:
      +materialized: ephemeral
      +schema: int_jira
```
In Github package dbt_package.yml file config
```
models:
  github:
    materialized: table
    intermediate:
      materialized: ephemeral
```

### Relevant error log or model output

```shell
NA
```

### Expected behavior

Should be creating int tables and model tables in the *_int_github and *_github location.

### dbt Project configurations

NA

### Package versions

  - package: fivetran/github
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.3

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
HI @rajan-lw thanks for raising this and opening the PRs to address the update! 

I agree with you that we should update the packages to build the models in the same format as our other packages by default. However, I did want to note that you can also define this in your root dbt_project.yml to override the package targets. See the [section in our README](https://github.com/fivetran/dbt_github#change-the-build-schema) for a description on how this can be done.

With that being said, we will likely accept your PRs and review to work to get the updates rolled out into the latest releases. One thing to note is that changing the target schema by default will result in breaking changes (v0.8.0 for dbt_github and v0.8.0 for dbt_github_source). As such, we will likely hold off on merging these until we have other breaking changes to integrate into the next breaking release. I will still review, but wanted to keep you updated on the status. 

Thanks again!

**Comment by fivetran-catfritz** [comment]
Hi @rajan-lw to update you, I will be adding in your target schema PRs in the next week or so. I will merge your PRs into my branches and then make some additional changes related to other issues. I'll post back here when it is released!
