### ISSUE TITLE
Formatting help

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_github#5]
@DylanBaker I'm having trouble figuring out the correct syntax for the `hours_request_review_to_first_review`, `hours_request_review_to_first_action` and `hours_request_review_to_merge` field calculations in the `pull_request_times` model.  Can you please take a look? The main issue is that I don't know how to use the dbt_utils.current_timestamp() macro when it's part of a coalesce. 

https://github.com/fivetran/dbt_github/blob/24663f3471127040ef5d37be75df5641986211cb/models/intermediate/pull_request_times.sql#L54

**Comment by DylanBaker** [comment]
Hey @fivetran-kristin. What's the error you're getting?

The way to use the dbt_utils.current_timestamp would be like this. You basically need to exit the string and concatenate in Jinja. `~` is how you concatenate in Jinja.

```sql
{{ dbt_utils.datediff(
    'time_of_first_request', 
    "least(
        coalesce(time_of_first_requested_reviewer_review, " ~ dbt.utils.current_timestamp() ~ "),
        coalesce(issue.closed_at, " ~ dbt.utils.current_timestamp() ~ "))", 
    'second') 
}} / 3600
```

**Comment by fivetran-kristin** [comment]
Thank you! This concatenate example is exactly what I needed.
